<?php
$host='localhost';
$user='lex94_commenter';
$password='sw[4KUM*!;J[';
$database='lex94_gh2011';
if(!$link=mysql_connect($host,$user,$password))
{
	exit();
}
else{
	mysql_select_db($database);
}	
?>
